### ISSUE TITLE
Working with [x]inetd

### ISSUE THREAD

**Issue by dluciv** [muffinista/gopher2000#3]
Hi! Great work, thank you very much!

Being actually very compact piece of software, this server, I guess, can benefit from an option to not listen on a port, but on STDIN. This will allow invoking it from inetd/xinetd. Gopher servers do not usually have high load, so I guess it will be quite ok to launch it for each request.

**Comment by muffinista** [comment]
Hi! An xinetd setup isn't a bad idea at all, but I probably won't have the time to implement it. I would happily accept a PR for it though. Thanks!
