### ISSUE TITLE
"About" page has broken link

### ISSUE THREAD

**Issue by xvxx** [muffinista/gopher2000#4]
[This line](https://github.com/muffinista/gopherpedia.com/blob/3781c69b574ca834df933cd8d1731ab79a7784e7/gopherpedia.rb#L87) should produce a text link, but instead generates this download link:

> 9more about the Gopher protocol    Gopher (protocol)    0.0.0.0    70

You can see it in action here:

https://gopherpedia.com/gopherpedia.com/about

The "back to gopherpedia" is broken too, also with the wrong host but the correct link type:

> 1back to gopherpedia    /    0.0.0.0    70

Separately, and I could be way off here, it seems like the `-o` option might also not be working in Gopher2000? Should it be `params[:host] = val`?

https://github.com/muffinista/gopher2000/blob/b024a6367513ffc218698e09e75a982329fc4011/bin/gopher2000#L34

I :heart: Gopherpedia, thank you!

**Comment by muffinista** [comment]
Thanks so much, nice catch!
