### ISSUE TITLE
HTTP links are not working in lynx

### ISSUE THREAD

**Issue by bebyx** [muffinista/gopher2000#9]
Hey, 

Something's wrong with the `http` command. IWhen I'm using lynx, it's not working at gopherpedia.com and I also cannot make it work on my development server.

**Comment by bebyx** [comment]
That might me useful to resolve the issue: https://programtalk.com/vs2/python/6272/pygopherd/jgoerzen-pygopherd-b794f8f/pygopherd/handlers/url.py/

Pygopherd handles web-urls smoothly in both terminal and GUI browsers.

**Comment by muffinista** [comment]
I think I see the problem, will try to have a fix out for it today.

**Comment by bebyx** [comment]
Thanks a lot, Collin!

With that feature fixed, the server will be truly awesome.

**Comment by muffinista** [comment]
Thanks so much for pointing this out! I think it's resolved now, if the server is asked to render a URL link it'll output something very similar to what pygopher does. I updated gopherpedia and tested an http link there, and it seems to be working.

**Comment by bebyx** [comment]
Checked it with lynx and gopher terminal browser - works great!

Thank you for the fix. Looking forward to publishing my hole with gopher2000. ^^
